--- !ruby/object:Jumpstart::Configuration
application_name: Airtable Fullfilfment
business_name: The Dragon Drop Development Company Limited
domain: example.com
support_email: support@example.com
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: false
solargraph: false
register_with_account: false
